---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
  - name: jfrog-cli
  - name: artifactory-resource-repo

outputs:
  - name: build-args

run:
  path: sh
  args:
  - -exc
  - |
    jq -n --arg version $(cat jfrog-cli/version) '{"JFROG_CLI_VERSION": $version}' > build-args/build-args.json
    cat jfrog-cli/version > build-args/version
