resources:
- name: jfrog-cli
  type: github-release
  source:
    owner: JFrogDev
    repository: jfrog-cli-go

- name: artifactory-resource-repo
  type: git
  source:
    repository: xetamus/artifactory-resource

- name: artifactory-resource-image
  type: docker-image
  source:
    repository: xetamus/artifactory-resource
    username: ((docker_username))
    password: ((docker_password))

jobs:
- name: push-docker-image
  plan:
  - aggregate:
    - get: jfrog-cli
      trigger: true
    - get: artifactory-resource-repo
  - task: generate-build-args
    file: artifactory-resource-repo/ci/tasks/generate-build-args/task.yml
  - put: artifactory-resource-image
    params:
      dockerfile: artifactory-resource-repo
      build_args_file: build-args/build-args.json
      tag: build-args/version